spring.application.name=condopay

# Configuração do banco de dados.
# O Spring Boot é inteligente e pode substituir esses valores por variáveis de ambiente
# com o mesmo nome (em maiúsculo e com _ em vez de .).
# Ex: SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, etc.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/condopay_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA (Hibernate)
# 'update': o Hibernate vai olhar suas entidades Java e criar/atualizar as tabelas no banco.
# Perfeito para desenvolvimento.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Formata o SQL para ficar bem indentado e legível no console
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do servidor
server.port=8081
